# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PushDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod ‘Firebase/Messaging’
  # Pods for PushDemo

  target 'PushDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PushDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

